package framework.enums;

public enum LoginType {

    // VALID
    VALID_CREDENTIALS,

    // INVALID CREDENTIALS
    INVALID_CREDENTIALS,
    INVALID_PASSWORD,

    // EMPTY / VALIDATION
    INVALID_EMAIL_FORMAT,
    EMPTY_FIELD,
    EMPTY_PASSWORD
}